[package]
name = "cargo-bpf"
version = "0.9.13"
description = "Cargo plugin to manage eBPF probes using redbpf"
repository = "https://github.com/redsift/redbpf"
documentation = "https://ingraind.org/api//cargo_bpf/"
authors = ["Alessandro Decina <alessandro.d@gmail.com>", "Peter Parkanyi <peter@redsift.io>"]
edition = "2018"
keywords = ["cargo", "redbpf", "bpf", "plugin", "subcommand"]
categories = ["development-tools::cargo-plugins"]
license = "MIT OR Apache-2.0"

[lib]
name = "cargo_bpf_lib"

[dependencies]
clap = "2.33"
bindgen = "0.51.1"
toml_edit = "0.1.5"
redbpf = { version = "^0.9.13", features = ["build", "load"], path = "../redbpf" }
futures = "0.3"
tokio = { version = "0.2.4", features = ["rt-core", "io-driver", "macros", "signal"] }
hexdump = "0.1"
libc = "0.2.66"
llvm-sys = "90"
syn = {version = "1.0", features = ["full", "visit", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
tempfile = "3.1"
